// <auto-generated />
using System;
using ContratacaoService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContratacaoService.Migrations
{
    [DbContext(typeof(ContratacaoDbContext))]
    [Migration("20250903190411_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ContratacaoService.Domain.Entities.Contratacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataContratacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId");

                    b.ToTable("Contratacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
